bash clean.sh; CUDA_VISIBLE_DEVICES=0 python3 main.py --dataset='tuberlin' --data_dir='/ssd_scratch/cvit/tuberlin' --nClasses=250 --workers=8 --epochs=600 --batch-size=512 --testbatchsize=16 --learningratescheduler='decayschedular' --decayinterval=50 --decaylevel=2 --optimType='adam' --nesterov --tenCrop --maxlr=0.001 --minlr=0.00005 --weightDecay=0 --binaryWeight --binStart=2 --binEnd=7 --model_def='sketchanetwbin' --inpsize=225 --name='tuberlin_sketchanetwbin_dualbin' | tee "textlogs/tuberlin_sketchanetwbin_dualbin.txt" &
bash clean.sh; CUDA_VISIBLE_DEVICES=1 python3 main.py --dataset='tuberlin' --data_dir='/ssd_scratch/cvit/tuberlin' --nClasses=250 --workers=8 --epochs=600 --batch-size=256 --testbatchsize=16 --learningratescheduler='decayschedular' --decayinterval=50 --decaylevel=2 --optimType='adam' --nesterov --tenCrop --maxlr=0.001 --minlr=0.00005 --weightDecay=0 --binaryWeight --binStart=2 --binEnd=100 --model_def='resnetwbin18' --inpsize=224 --name='tuberlin_resnetwbin18_dualbin' | tee "textlogs/tuberlin_resnetwbin18_dualbin.txt" &
bash clean.sh; CUDA_VISIBLE_DEVICES=2 python3 main.py --dataset='tuberlin' --data_dir='/ssd_scratch/cvit/tuberlin' --nClasses=250 --workers=8 --epochs=600 --batch-size=128 --testbatchsize=4 --learningratescheduler='decayschedular' --decayinterval=50 --decaylevel=2 --optimType='adam' --nesterov --tenCrop --maxlr=0.001 --minlr=0.00005 --weightDecay=0 --binaryWeight --binStart=2 --binEnd=100 --model_def='squeezenetwbin' --inpsize=224 --name='tuberlin_squeezenetwbin_dualbin' | tee "textlogs/tuberlin_squeezenetwbin_dualbin.txt" &

bash clean.sh; CUDA_VISIBLE_DEVICES=0 python3 main.py --dataset='sketchy' --data_dir='/ssd_scratch/cvit/sketchyrecognition' --nClasses=125 --workers=8 --epochs=400 --batch-size=256 --testbatchsize=16 --learningratescheduler='decayschedular' --decayinterval=50 --decaylevel=2 --optimType='adam' --nesterov --tenCrop --maxlr=0.001 --minlr=0.00005 --weightDecay=0 --binaryWeight --binStart=2 --binEnd=7 --model_def='sketchanetwbin' --inpsize=225 --name='sketchy_sketchanetwbin_dualbin' | tee "textlogs/sketchy_sketchanetwbin_dualbin.txt" &
bash clean.sh; CUDA_VISIBLE_DEVICES=1 python3 main.py --dataset='sketchy' --data_dir='/ssd_scratch/cvit/sketchyrecognition' --nClasses=125 --workers=8 --epochs=400 --batch-size=128 --testbatchsize=16 --learningratescheduler='decayschedular' --decayinterval=50 --decaylevel=2 --optimType='adam' --nesterov --tenCrop --maxlr=0.001 --minlr=0.00005 --weightDecay=0 --binaryWeight --binStart=2 --binEnd=100 --model_def='resnetwbin18' --inpsize=224 --name='sketchy_resnetwbin18_dualbin' | tee "textlogs/sketchy_resnetwbin18_dualbin.txt" &
bash clean.sh; CUDA_VISIBLE_DEVICES=2 python3 main.py --dataset='sketchy' --data_dir='/ssd_scratch/cvit/sketchyrecognition' --nClasses=125 --workers=8 --epochs=400 --batch-size=96 --testbatchsize=4 --learningratescheduler='decayschedular' --decayinterval=50 --decaylevel=2 --optimType='adam' --nesterov --tenCrop --maxlr=0.001 --minlr=0.00005 --weightDecay=0 --binaryWeight --binStart=2 --binEnd=100 --model_def='squeezenetwbin' --inpsize=224 --name='sketchy_squeezenetwbin_dualbin' | tee "textlogs/sketchy_squeezenetwbin_dualbin.txt" &

bash clean.sh; CUDA_VISIBLE_DEVICES=0 python main.py --dataset='imagenet12' --data_dir='/ssd_scratch/cvit/Imagenet12' --nClasses=1000 --workers=8  --epochs=70 --batch-size=128 --testbatchsize=32 --learningratescheduler='decayschedular' --decayinterval=8 --decaylevel=2 --optimType='adam' --verbose --maxlr=0.0005 --minlr=0.00001 --binStart=2 --binEnd=8 --binaryWeight --weightDecay=0 --model_def='alexnetwbin' --inpsize=224 --name='imagenet_alexnetwbin' | tee "textlogs/imagenet_alexnetwbin.txt" &
bash clean.sh; CUDA_VISIBLE_DEVICES=1 python main.py --dataset='imagenet12' --data_dir='/ssd_scratch/cvit/Imagenet12' --nClasses=1000 --workers=8  --epochs=70 --batch-size=128 --testbatchsize=32 --learningratescheduler='decayschedular' --decayinterval=8 --decaylevel=2 --optimType='adam' --verbose --maxlr=0.0005 --minlr=0.00001 --binStart=2 --binEnd=100 --binaryWeight --weightDecay=0 --model_def='resnetwbin18' --inpsize=224 --name='imagenet_resnetwbin18' | tee "textlogs/imagenet_resnetwbin18.txt" &
bash clean.sh; CUDA_VISIBLE_DEVICES=2 python main.py --dataset='imagenet12' --data_dir='/ssd_scratch/cvit/Imagenet12' --nClasses=1000 --workers=8  --epochs=70 --batch-size=128 --testbatchsize=32 --learningratescheduler='decayschedular' --decayinterval=8 --decaylevel=2 --optimType='adam' --verbose --maxlr=0.0005 --minlr=0.00001 --binStart=2 --binEnd=100 --binaryWeight --weightDecay=0 --model_def='squeezenetwbin' --inpsize=224 --name='imagenet_squeezenetwbin' | tee "textlogs/imagenet_squeezenetwbin.txt" &
